### ISSUE TITLE
Build error with the latest liquid-dsp

### ISSUE THREAD

**Issue by ra1nb0w** [pothosware/PothosLiquidDSP#9]
Liquid-dsp did a change on `firhilbf_c2r_execute()` and now require 4 parameters; the [documentation](https://liquidsdr.org/doc/firhilb/) is not updated.
```c++
/* from liquid.h */
void firhilbf_c2r_execute(firhilbf _q, liquid_float_complex _x, float * _y0, float * _y1);
```
therefore when building I receive the following error
```make
/Users/user/tmp/PothosLiquidDSP/build/firhilbf.cpp:176:13: error: no matching function for call to 'firhilbf_c2r_execute'
            firhilbf_c2r_execute(_q, *inxBuff, outyBuff);
            ^~~~~~~~~~~~~~~~~~~~
/opt/local/include/liquid/liquid.h:2702:27: note: candidate function not viable: requires 4 arguments, but 3 were provided
LIQUID_FIRHILB_DEFINE_API(LIQUID_FIRHILB_MANGLE_FLOAT, float, liquid_float_complex)
```
Change example can be seen at [github](https://github.com/jgaeddert/liquid-dsp/commit/af9ff95bc03adfca464124e2cf6f554fc6054e3d).

Moreover, just FYI, I see the following warning
```make
/opt/local/include/liquid/liquid.h:6034:24: warning: 'polycf_interp_lagrange' has C-linkage specified, but returns user-defined type 'liquid_float_complex' (aka 'complex<float>') which is incompatible with C [-Wreturn-type-c-linkage]
/opt/local/include/liquid/liquid.h:6034:24: warning: 'polycf_val_lagrange_barycentric' has C-linkage specified, but returns user-defined type 'liquid_float_complex' (aka 'complex<float>') which is incompatible with C [-Wreturn-type-c-linkage]
/opt/local/include/liquid/liquid.h:6446:26: warning: 'matrixcf_det' has C-linkage specified, but returns user-defined type 'liquid_float_complex' (aka 'complex<float>') which is incompatible with C [-Wreturn-type-c-linkage]
LIQUID_MATRIX_DEFINE_API(LIQUID_MATRIX_MANGLE_CFLOAT,  liquid_float_complex)
                         ^
/opt/local/include/liquid/liquid.h:6447:26: warning: 'matrixc_det' has C-linkage specified, but returns user-defined type 'liquid_double_complex' (aka 'complex<double>') which is incompatible with C [-Wreturn-type-c-linkage]
LIQUID_MATRIX_DEFINE_API(LIQUID_MATRIX_MANGLE_CDOUBLE, liquid_double_complex)
                         ^
/opt/local/include/liquid/liquid.h:7761:25: warning: 'synth_crcf_get_half_previous' has C-linkage specified, but returns user-defined type 'liquid_float_complex' (aka 'complex<float>') which is incompatible with C [-Wreturn-type-c-linkage]
/opt/local/include/liquid/liquid.h:7761:25: warning: 'synth_crcf_get_half_next' has C-linkage specified, but returns user-defined type 'liquid_float_complex' (aka 'complex<float>') which is incompatible with C [-Wreturn-type-c-linkage]
```
Test done with the latest commit of [liquid-dsp](https://github.com/jgaeddert/liquid-dsp) branch master. Thank you.

**Comment by ra1nb0w** [comment]
Side note: add `build/` to `.gitignore`. thanks

**Comment by guruofquality** [comment]
Fixed: https://github.com/pothosware/PothosLiquidDSP/commit/bb1e1dcd2b8c790150a947b0ea1816475469b6ab

> /opt/local/include/liquid/liquid.h:6034:24: warning: 'polycf_interp_lagrange' has C-linkage specified, but returns user-defined type 'liquid_float_complex' (aka 'complex<float>') which is incompatible with C [-Wreturn-type-c-linkage]

I'm not seeing the warings, at least on ubuntu 18.04 LTS. liquid can be a little weird in C++, basically it typedefs the complex data pointers differently in C++ when `<complex>` is included. I don't think that works very well for return values which don't amount to just different pointer casts. Although I dont think we use those particular calls, its something you would need to take up with liquid dsp, its API, and complex number typedefs

**Comment by ra1nb0w** [comment]
thank you.
Sorry, I didn't said the platform: macOS 10.14 and clang.
Ok, I will report to liquid-dsp.
